sudo: required
dist: bionic
language: python
services:
  - postgresql
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
before_script:
  - psql -c 'CREATE ROLE jahid WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE REPLICATION ENCRYPTED PASSWORD 'md5709c4fb68f87bdae8d9698d2f3368dc6';' -U postgres
  - psql -c 'CREATE DATABASE test WITH  OWNER = jahid ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8' TABLESPACE = pg_default CONNECTION LIMIT = -1;' -U postgres
script: 
  - ./run_tests.sh
after_success:
  - pip install coveralls
  - coveralls

