sudo: required
dist: bionic
language: python
services:
  - postgresql
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
before_script:
  - sh ./.travis_before_script.sh
script: 
  - ./run_tests.sh
after_success:
  - pip install coveralls
  - coveralls

