#!/bin/sh
psql -c "CREATE ROLE jahid WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE REPLICATION ENCRYPTED PASSWORD 'md5709c4fb68f87bdae8d9698d2f3368dc6';" -U postgres
psql -c "CREATE DATABASE test WITH  OWNER = jahid ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8' TABLESPACE = pg_default CONNECTION LIMIT = -1;" -U postgres
